name: PHPCS Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    name: Run PHP_CodeSniffer
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: PHP settings
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Change the php version
          tools: composer

      # Step 3: Install dependencies
      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      # Step 4: Run PHP_CodeSniffer
      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=WordPress --ignore=vendor/*,node_modules/* .

